### ISSUE TITLE
NoSuchMethodException when trying to randomize com.google.protobuf.MapEntry class

### ISSUE THREAD

**Issue by fercam24** [murdos/easy-random-protobuf#77]
Hello, 

I'm actually trying to use your amazing library but without success. 

I used the exact same example you put in your README.

I have a class that has a property of type [MapEntry](https://github.com/protocolbuffers/protobuf/blob/master/java/core/src/main/java/com/google/protobuf/MapEntry.java) (from com.google.protobuf) in it. And whenever I try to randomize it I keep getting this error:

```Unable to create a random instance of type class openmatch.Messages$Assignment
org.jeasy.random.ObjectCreationException: Unable to create a random instance of type class openmatch.Messages$Assignment
...
Caused by: org.jeasy.random.ObjectCreationException: Unable to create a random instance of type class com.google.protobuf.MapEntry
	at app//org.jeasy.random.EasyRandom.doPopulateBean(EasyRandom.java:172)
	at app//org.jeasy.random.EasyRandom.nextObject(EasyRandom.java:100)
	at app//io.github.murdos.easyrandom.protobuf.ProtobufMessageRandomizer.lambda$new$8(ProtobufMessageRandomizer.java:77)
	at app//io.github.murdos.easyrandom.protobuf.ProtobufMessageRandomizer.populateField(ProtobufMessageRandomizer.java:121)
	at app//io.github.murdos.easyrandom.protobuf.ProtobufMessageRandomizer.getRandomValue(ProtobufMessageRandomizer.java:95)
	at app//io.github.murdos.easyrandom.protobuf.ProtobufMessageRandomizer.getRandomValue(ProtobufMessageRandomizer.java:43)
	at app//org.jeasy.random.EasyRandom.doPopulateBean(EasyRandom.java:133)
	... 88 more
Caused by: java.lang.IllegalArgumentException: java.lang.NoSuchMethodException: com.google.protobuf.MapEntry.getDefaultInstance()
	at io.github.murdos.easyrandom.protobuf.ProtobufMessageRandomizer.instantiateMessage(ProtobufMessageRandomizer.java:108)
	at io.github.murdos.easyrandom.protobuf.ProtobufMessageRandomizer.getRandomValue(ProtobufMessageRandomizer.java:85)
	at io.github.murdos.easyrandom.protobuf.ProtobufMessageRandomizer.getRandomValue(ProtobufMessageRandomizer.java:43)
	at org.jeasy.random.EasyRandom.doPopulateBean(EasyRandom.java:133)
	... 94 more
Caused by: java.lang.NoSuchMethodException: com.google.protobuf.MapEntry.getDefaultInstance()
	at java.base/java.lang.Class.getMethod(Class.java:2108)
	at io.github.murdos.easyrandom.protobuf.ProtobufMessageRandomizer.instantiateMessage(ProtobufMessageRandomizer.java:105)
	... 97 more
```

Do you, by chance, have already been facing that kind of problem? and is there any solution/workaround? 

Thanks

**Comment by murdos** [comment]
[Maps](https://developers.google.com/protocol-buffers/docs/proto3#maps) are not indeed not supported, mainly because I'm not  using them.
I've started investigating how to generate them, and I'll let you know when I've something usable.

**Comment by fercam24** [comment]
Right I understand. Thanks a lot for your reply.

**Comment by murdos** [comment]
@fercam24 : I just released a new version that handles maps. Please let me know if you have any issue with it.
